// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppBreadcrumbItem: typeof import('./src/components/elements/breadcrumbs/AppBreadcrumbItem.vue')['default']
    AppBreadcrumbs: typeof import('./src/components/elements/breadcrumbs/AppBreadcrumbs.vue')['default']
    AppContainer: typeof import('./src/components/layout/page/AppContainer.vue')['default']
    AppFormLayout: typeof import('./src/components/layout/form/AppFormLayout.vue')['default']
    AppFormLayoutSection: typeof import('./src/components/layout/form/AppFormLayoutSection.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppLink: typeof import('./src/components/elements/AppLink.vue')['default']
    AppPageContent: typeof import('./src/components/layout/page/AppPageContent.vue')['default']
    AppPageHeader: typeof import('./src/components/layout/page/AppPageHeader.vue')['default']
    AppPageLoader: typeof import('./src/components/layout/AppPageLoader.vue')['default']
    AppRouterLink: typeof import('./src/components/elements/AppRouterLink.vue')['default']
    AppTable: typeof import('./src/components/elements/table/AppTable.vue')['default']
    AppTableTr: typeof import('./src/components/elements/table/AppTableTr.vue')['default']
    AppText: typeof import('./src/components/typography/AppText.vue')['default']
    AuthLayout: typeof import('./src/modules/auth/components/AuthLayout.vue')['default']
    AuthPage: typeof import('./src/modules/auth/components/AuthPage.vue')['default']
    CenterContent: typeof import('./src/components/ui/CenterContent.vue')['default']
    ExtendedRouterLink: typeof import('./src/components/elements/router/ExtendedRouterLink.vue')['default']
    ForgotPasswordFormView: typeof import('./src/modules/auth/forgot-password-form/views/ForgotPasswordFormView.vue')['default']
    FormButton: typeof import('./src/components/elements/form/FormButton.vue')['default']
    FormSpacer: typeof import('./src/components/elements/form/FormSpacer.vue')['default']
    LoginFormTestAccounts: typeof import('./src/modules/auth/login-form/components/LoginFormTestAccounts.vue')['default']
    LoginFormView: typeof import('./src/modules/auth/login-form/views/LoginFormView.vue')['default']
    NestedFormContactDetails: typeof import('./src/modules/nested/nested-form/components/NestedFormContactDetails.vue')['default']
    NestedFormEmail: typeof import('./src/modules/auth/nested-form/components/NestedFormEmail.vue')['default']
    NestedFormName: typeof import('./src/modules/auth/nested-form/components/NestedFormName.vue')['default']
    NestedFormUserInfo: typeof import('./src/modules/nested/nested-form/components/NestedFormUserInfo.vue')['default']
    NestedFormView: typeof import('./src/modules/nested/nested-form/views/NestedFormView.vue')['default']
    ResetPasswordFormView: typeof import('./src/modules/auth/reset-password-form/views/ResetPasswordFormView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuspenseError: typeof import('./src/components/suspense/SuspenseError.vue')['default']
    SuspenseWrapper: typeof import('./src/components/suspense/SuspenseWrapper.vue')['default']
    Test: typeof import('./src/Test.vue')['default']
    Test2: typeof import('./src/Test2.vue')['default']
    TestA: typeof import('./src/modules/test/TestA.vue')['default']
    TestB: typeof import('./src/modules/test/TestB.vue')['default']
    TestWrapper: typeof import('./src/modules/test/TestWrapper.vue')['default']
  }
}
