// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    AppLink: typeof import('./src/components/elements/AppLink.vue')['default']
    AuthLayout: typeof import('./src/modules/auth/components/AuthLayout.vue')['default']
    AuthPage: typeof import('./src/modules/auth/components/AuthPage.vue')['default']
    CenterContent: typeof import('./src/components/ui/CenterContent.vue')['default']
    ForgotPasswordFormView: typeof import('./src/modules/auth/forgot-password-form/views/ForgotPasswordFormView.vue')['default']
    FormButton: typeof import('./src/components/form/FormButton.vue')['default']
    FormSpacer: typeof import('./src/components/form/FormSpacer.vue')['default']
    LoginFormTestAccounts: typeof import('./src/modules/auth/login-form/components/LoginFormTestAccounts.vue')['default']
    LoginFormView: typeof import('./src/modules/auth/login-form/views/LoginFormView.vue')['default']
    ResetPasswordFormView: typeof import('./src/modules/auth/reset-password-form/views/ResetPasswordFormView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SuspenseError: typeof import('./src/components/suspense/SuspenseError.vue')['default']
    SuspenseWrapper: typeof import('./src/components/suspense/SuspenseWrapper.vue')['default']
    Test: typeof import('./src/modules/Test.vue')['default']
  }
}
